  version: "3"
  services:
    django:
      build: .
      container_name: RegisterApi
      ports:
        - "8000:8000"
      volumes:
        - .:/app
        - static_volume:/usr/src/app/back-static
        - media_volumes:/usr/src/app/back-media
      restart: always
      depends_on:
        - pgdb
        - redis
      command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    celery:
      build: .
      command: celery -A core worker -l INFO
      volumes:
        - .:/usr/src/app
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
      depends_on:
        - django
        - redis
    pgdb:
      image: postgres:alpine3.19
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
      container_name: pgdb
      volumes:
        - db_data:/var/lib/postgresql/data/
      ports:
        - "5438:5432"
    nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/usr/src/app/back-static
        - media_volumes:/usr/src/app/back-media
      depends_on:
        - django
    redis:
      image: "redis:alpine"

  volumes:
    static_volume:
    media_volumes:
    db_data:
